version: "2.4"
services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - published: "${MCP_ATLASSIAN_PORT}"
        target: "${MCP_ATLASSIAN_PORT}"
    env_file:
      - .secrets/mcp-atlassian.env
    command: ["--transport", "sse", "--port", "${MCP_ATLASSIAN_PORT}", "-vv"]
    restart: unless-stopped

  goose:
    depends_on:
      - mcp-atlassian
    image: goose-container
    build:
      context: ./goose-container
      dockerfile: Containerfile
    env_file:
      - .secrets/goose.env
    volumes:
      - home-goose-persistent:/home/goose
      - ./goose-recipes:/home/goose/recipes:ro,z
      - ./goose-container/goose-config.yaml:/home/goose/.config/goose/config.yaml:ro,z
      - ./goose-container/wait_mcp_server.sh:/home/goose/wait_mcp_server.sh:ro,z
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  home-goose-persistent:
