services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    command: ["--transport", "sse", "--port", "9000", "-vv"]
    restart: unless-stopped

  adk-agent:
    depends_on:
      - mcp-atlassian
    image: adk-agent
    build:
      context: .
      dockerfile: Containerfile
    env_file:
      - .env
    environment:
      - MCP_JIRA_URL=http://mcp-atlassian:9000/sse
    volumes:
      - ./agents:/home/adk/agents:ro,z
      - ./wait_mcp_server.sh:/wait_mcp_server.sh:ro,z
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  adk-data:
